language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ./jasonlewis/basset ./laravel/bundles/babel
  - echo "<?php return array('basset' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "php artisan test basset"